<?php

namespace GuideBundle\Repository;

/**
 * ActorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActorsRepository extends \Doctrine\ORM\EntityRepository
{
}
