<?php

namespace GuideBundle\Repository;

/**
 * AlergiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlergiesRepository extends \Doctrine\ORM\EntityRepository
{
}
