<?php

namespace GuideBundle\Repository;

/**
 * AllergyToMedicineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllergyToMedicineRepository extends \Doctrine\ORM\EntityRepository
{
}
