<?php

namespace GuideBundle\Repository;

/**
 * AnalysResRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalysResRepository extends \Doctrine\ORM\EntityRepository
{
}
