<?php

namespace GuideBundle\Repository;

/**
 * ChronicIllnessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChronicIllnessRepository extends \Doctrine\ORM\EntityRepository
{
}
