<?php

namespace GuideBundle\Repository;

/**
 * CIllnessToMedicineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CIllnessToMedicineRepository extends \Doctrine\ORM\EntityRepository
{
}
