<?php

namespace GuideBundle\Repository;

/**
 * ConfPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfPersonRepository extends \Doctrine\ORM\EntityRepository
{
}
