<?php

namespace GuideBundle\Repository;

/**
 * DistricsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistricsRepository extends \Doctrine\ORM\EntityRepository
{
}
