<?php

namespace GuideBundle\Repository;

/**
 * IllnessesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IllnessesRepository extends \Doctrine\ORM\EntityRepository
{
}
