<?php

namespace GuideBundle\Repository;

/**
 * MedicalStaffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicalStaffRepository extends \Doctrine\ORM\EntityRepository
{
}
