<?php

namespace GuideBundle\Repository;

/**
 * MedicinesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicinesRepository extends \Doctrine\ORM\EntityRepository
{
}
