<?php

namespace GuideBundle\Repository;

/**
 * PatientCharacteristicsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientCharacteristicsRepository extends \Doctrine\ORM\EntityRepository
{
}
