<?php

namespace GuideBundle\Repository;

/**
 * RegInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
