<?php

namespace GuideBundle\Repository;

/**
 * SymptToIllnessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SymptToIllnessRepository extends \Doctrine\ORM\EntityRepository
{
}
