<?php

namespace GuideBundle\Repository;

/**
 * VisitTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
