<?php

namespace GuideBundle\Repository;

/**
 * VisitToIllnessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitToIllnessRepository extends \Doctrine\ORM\EntityRepository
{
}
