<?php

namespace GuideBundle\Repository;

/**
 * VisitToMedicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitToMedicRepository extends \Doctrine\ORM\EntityRepository
{
}
