guide_timetable:
    resource: "@GuideBundle/Controller/TimetableController.php"
    type:     annotation

schedule:
    resource: "@ScheduleBundle/Controller/"
    type:     annotation

app:
    resource: "@GuideBundle/Controller/"
    type:     annotation


