app:
    resource: "@GuideBundle/Controller/"
    type:     annotation
admin:
    path: /admin
    defaults: {_controller: GuideBundle:MedicalStaff:index}

auth:
    path: /auth
    defaults: {_controller: GuideBundle:Security:login}

logout:
    path:   /logout
    defaults: {_controller: GuideBundle:MedicalStaff:logout}


